### ISSUE TITLE
Add prettier dev dependency

### ISSUE THREAD

**Issue by jimmyandrade** [multei/api#58]
## Description

Currently, there is no tool to help ensure that the code follows a common style.
Installing and configuring the Prettier would help ensure that.

Prettier was elected as the standard for the Multei! project, and it can help to prevent errors like  [semicolon insertion (detected from LGTM)](https://lgtm.com/projects/g/multei/api/alerts/?mode=list)

Check this example at [`/migrations/20200216123623_create_parkings_table.js`](https://lgtm.com/projects/g/multei/api/snapshot/faf4014548bfbfae89e1e9ab37d06f9d5b1eda9a/files/migrations/20200216123623_create_parkings_table.js?sort=name&dir=ASC&mode=heatmap#x41b75a890d546f3a:1)

## Tasks

- [ ] Run `npm install prettier --save-dev --save-exact` on Terminal;
- [ ] Add `format` to `package.json` scripts with prettier command to format JS and MD files;
- [ ] Add the [Prettier badge](https://www.npmjs.com/package/prettier#badge) to `README.md`.

## Additional context

- [prettier package on npm](https://www.npmjs.com/package/prettier);
- [Multei! API code alerts](https://lgtm.com/projects/g/multei/api/alerts/?mode=list);

**Comment by jimmyandrade** [comment]
Won't fix. We will adopt `eslint`.
